// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPgKdbQDWetF_P1SC9TiaJVdFf4hwX-k',
    appId: '1:892490711823:web:8e4e17eb534aae0500f47a',
    messagingSenderId: '892490711823',
    projectId: 'binbuddy-8df97',
    authDomain: 'binbuddy-8df97.firebaseapp.com',
    storageBucket: 'binbuddy-8df97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLsRyHOrOMAYKuKoTfVSPdq0W36HHzgE',
    appId: '1:892490711823:android:33c43c53578942d900f47a',
    messagingSenderId: '892490711823',
    projectId: 'binbuddy-8df97',
    storageBucket: 'binbuddy-8df97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9dzBMKbPRv6mkscvNtkIfDOHUvgs8-8',
    appId: '1:892490711823:ios:91da4810b43f7e8300f47a',
    messagingSenderId: '892490711823',
    projectId: 'binbuddy-8df97',
    storageBucket: 'binbuddy-8df97.appspot.com',
    iosBundleId: 'com.example.binbuddyFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9dzBMKbPRv6mkscvNtkIfDOHUvgs8-8',
    appId: '1:892490711823:ios:2385fd43aadd244e00f47a',
    messagingSenderId: '892490711823',
    projectId: 'binbuddy-8df97',
    storageBucket: 'binbuddy-8df97.appspot.com',
    iosBundleId: 'com.example.binbuddyFrontend.RunnerTests',
  );
}
